channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Cartopy
  - pip
  - pip:
    - xarray
    - requests
    - aiohttp
    - intake
    - git+https://github.com/intake/intake-xarray@master#egg=intake-xarray
    - pydap
    - pyyaml
    - typhon
    - tqdm
    - nbgitpuller
